#NUMPY
##PARTE A
###Ejercicio 1.0
Importar los módulos necesarios

In [1]:
import numpy as np
import math

##Ejercicio 1.1
Calculemos el producto matricial, la matriz transpuesta y el determinante.

In [2]:
matrizA = np.array([[5,6],[7,8]])
matrizB = np.array ([[8,9],[10,11]])

In [13]:
producto_matricial = np.matmul(matrizA, matrizB)
transpuesta = np.transpose(matrizA)
determinante = np.linalg.det(matrizA)

print ("Producto matricial:","\n", producto_matricial,"\n\n","transpuesta:","\n",transpuesta,"\n\n","Determinante:","\n",determinante)

Producto matricial: 
 [[100 111]
 [136 151]] 

 transpuesta: 
 [[5 7]
 [6 8]] 

 Determinante: 
 -2.000000000000005


##Ejercicio 1.2
Numpy tiene una función especifica para resolver ecuaciones lineales

In [22]:
coeficientes = np.array([[2, 3], [4, -1]])
constantes = np.array([5, 2])
#donde 2x + 3y = 5
#  4x + (-1y) = 2

solucion = np.linalg.solve(coeficientes, constantes)
print("Solución del sistema de ecuaciones:")
print("x =", solucion[0])
print("y =", solucion[1])

Solución del sistema de ecuaciones:
x = 0.7857142857142857
y = 1.1428571428571428


La función np.linalg.solve resuelve este sistema de ecuaciones lineales, encontrando los valores de x y y que satisfacen ambas ecuaciones simultáneamente.

##Ejercicio 1.3
Exploremos funciones para conocer las dimensiones de un array multidimensional

In [23]:
array_multidimensional = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
                                    [[0, 1, 2, 3],[4, 5, 6, 7]],
                                     [[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [24]:
array_multidimensional.ndim

3

##ndim
 es un atributo de los arrays de NumPy que devuelve el número de dimensiones del array. En otras palabras, indica cuántos ejes tiene el array.

In [25]:
array_multidimensional.size

24


##.size
en NumPy devuelve el número total de elementos en el array. En otras palabras, indica el tamaño total del array contando todos los elementos.

In [26]:
array_multidimensional.shape

(3, 2, 4)

##.shape
 en NumPy devuelve una tupla que describe la forma (shape) o la estructura del array. Esta tupla indica el número de elementos en cada dimensión del array.

 Por lo tanto, la tupla de forma (3, 2, 4) indica que hay 3 elementos en la primera dimensión, 2 elementos en la segunda dimensión y 4 elementos en la tercera dimensión.

##Ejercicio 1.4
Veamos que posibilidades hay para indexar valores y separar un array

In [27]:
array_indexado = np.array([1, 2, 3, 4, 5, 6, 7])

In [28]:

array_indexado[0]

1

In [29]:
array_indexado[0:2]

array([1, 2])

que va del indice 0 hasta el indice 1 por que el indice 2 no es inclusivo

In [30]:
array_indexado[4:]

array([5, 6, 7])

que va desde el indice 4 hasta el ultimo indice del array

##Ejercicio 1.5
Veamos como utilizar la funcion sort

In [31]:
array_desordenado = np.array([3, 1, 5, 2, 4])

array_ordenado = np.sort(array_desordenado)

array_ordenado

array([1, 2, 3, 4, 5])

## sort
ordena el array

##Ejericio 1.6
Ademas de ordernar un array podemos invertir el orden de los valores

In [32]:
array_original = np.array([1, 2, 3, 4, 11, 12, 13, 14, 15, 5, 6, 7, 8])

array_reverso = np.flip(array_original)
array_reverso

array([ 8,  7,  6,  5, 15, 14, 13, 12, 11,  4,  3,  2,  1])

##flip
invierte en un giro de 180° el orden de los indices del array

##Ejercicio 1.7
Crear un array con numeros aleatorios

In [33]:
rng = np.random.default_rng()

In [34]:
rng.random(3)

array([0.49973665, 0.55105782, 0.34523242])

##np.random
default_rng es una función que te permite crear un generador de números aleatorios predeterminado en NumPy, que puede ser utilizado para generar secuencias de números aleatorios para diversas aplicaciones.

In [35]:
rng.integers(5, size=(2, 4))

array([[4, 1, 3, 1],
       [1, 3, 1, 3]])

rng.integers(5, size=(2, 4)) es una función que genera una matriz de números enteros aleatorios entre 0 (inclusive) y 5 (exclusivo) con una forma de (2, 4). Aquí está la explicación detallada:

rng: Es un objeto de generador de números aleatorios creado con np.random.default_rng(). Este objeto se utiliza para generar números aleatorios de diferentes distribuciones.

.integers: Es un método del objeto de generador de números aleatorios (rng) que se utiliza para generar números enteros aleatorios dentro de un rango dado.

5: Es el límite superior del rango de valores enteros aleatorios. En este caso, genera números enteros aleatorios entre 0 (inclusive) y 5 (exclusivo), lo que significa que los números generados estarán en el rango [0, 5).

size=(2, 4): Es el tamaño o forma de la matriz que se va a generar. En este caso, se genera una matriz con 2 filas y 4 columnas.

Por lo tanto, rng.integers(5, size=(2, 4)) generará una matriz de números enteros aleatorios con una forma de (2, 4), donde cada número estará en el rango de 0 a 4.

##Ejercicio 1.8
Contar valores unicos dentro de un array

In [36]:
array_repetidos = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20, 11, 12, 13, 14, 15, 16, 17, 11, 14, 18, 19, 20])

array_unicos= np.unique(array_repetidos)
array_unicos

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##unique
filtra entre valores repetidos de un array y entrega valores unicos

##Parte A
Tenemos una función cúbica con la forma (3x^3-7x^2+6*x+9)

In [37]:
def mi_funcion(x):
    return 3 * x**3 - 7 * x**2 + 6 * x + 9

##Ejercicio 2.1
Calcular cuales serian los valores obtenidos al pasarle como argumentos los valores pares desde 0 a 20 incluyendo ambos. Guardar el resultado en un array.

In [38]:
lista_valores_x = []
for i in range(0, 21, 2):
    lista_valores_x.append(i)
input_array = np.array(lista_valores_x)
input_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Inicialización de la lista: Se crea una lista vacía llamada lista_valores_x.

Bucle for: Se utiliza un bucle for para iterar sobre los números pares desde 0 hasta 20 (ambos incluidos), con un paso de 2 en 2. Esto se logra con el rango range(0, 21, 2), donde el tercer argumento especifica el paso.

Adición de valores a la lista: En cada iteración del bucle, el valor actual i, que es un número par, se agrega a la lista lista_valores_x utilizando el método append().

Creación del array de NumPy: Después de que el bucle haya terminado de ejecutarse, se utiliza la función np.array() de NumPy para convertir la lista lista_valores_x en un array de NumPy. Este array contendrá todos los valores pares del 0 al 20, incluidos ambos.

El resultado final es un array de NumPy llamado input_array que contiene los valores pares del 0 al 20, incluidos ambos.

In [39]:
output_array = mi_funcion(input_array)
output_array

array([    9,    17,   113,   441,  1145,  2369,  4257,  6953, 10601,
       15345, 21329])

Dado que mi_funcion toma un array x como entrada y aplica una serie de operaciones matemáticas a cada elemento del array, podemos inferir que output_array contendrá los resultados de aplicar estas operaciones a cada valor en input_array.

Entonces, output_array contendrá los resultados de evaluar la expresión
3
�
3
−
7
�
2
+
6
�
+
9
3x
3
 −7x
2
 +6x+9 para cada valor en input_array. Es decir, para cada valor x en input_array, output_array contendrá el resultado de calcular
3
�
3
−
7
�
2
+
6
�
+
9
3x
3
 −7x
2
 +6x+9.

Si ejecutas el código con input_array que contiene valores pares del 0 al 20 (incluyendo ambos), output_array contendrá los resultados de evaluar la función mi_funcion en cada uno de esos valores.

##Ejercicio 2.2
Al array que obtuvimos en la sección anterior:

Calcula la media de los números en el array que contiene los valores calculados.
Calcula la desviación estándar de los números en el array calculado.
Encuentra el valor máximo y su índice en el array calculado.
Crea un nuevo array array_cuadrados que contenga el cuadrado de cada número en calculado.
Crear un array con la suma acumulativa (a1, a1+a2, a1+a2+a3, .....) de los elementos en array_cuadrados.
Crear un array con la raiz 5ta de cada valor de array_cuadrados (redondear a 2 decimales).
Imprimir los resultados obtenidos.

In [40]:
media = np.mean(output_array)

desviacion_estandar = np.std(output_array)

valor_maximo = np.max(output_array)

indice_maximo = np.argmax(output_array)

array_cuadrados = np.square(output_array)

suma_acumulativa_cuadrados = np.cumsum(array_cuadrados)

array_raiz_quinta = np.power(array_cuadrados, 1/5).round(2)

print("Media:", media)
print("Desviación Estándar:", desviacion_estandar)
print("Valor Máximo:", valor_maximo)
print("Índice del Valor Máximo:", indice_maximo)
print("Valores al Cuadrado:", array_cuadrados)
print("Array Suma Acumulativa de Valores al Cuadrado:", suma_acumulativa_cuadrados)
print("Array Resultado Raiz Quinta:", array_raiz_quinta)

Media: 5689.0
Desviación Estándar: 6877.906658279102
Valor Máximo: 21329
Índice del Valor Máximo: 10
Valores al Cuadrado: [       81       289     12769    194481   1311025   5612161  18122049
  48344209 112381201 235469025 454926241]
Array Suma Acumulativa de Valores al Cuadrado: [       81       370     13139    207620   1518645   7130806  25252855
  73597064 185978265 421447290 876373531]
Array Resultado Raiz Quinta: [ 2.41  3.11  6.63 11.42 16.73 22.38 28.29 34.42 40.75 47.25 53.9 ]


media = np.mean(output_array): Calcula la media aritmética de los valores en output_array.

desviacion_estandar = np.std(output_array): Calcula la desviación estándar de los valores en output_array.

valor_maximo = np.max(output_array): Encuentra el valor máximo en output_array.

indice_maximo = np.argmax(output_array): Encuentra el índice del valor máximo en output_array.

array_cuadrados = np.square(output_array): Calcula el cuadrado de cada valor en output_array.

suma_acumulativa_cuadrados = np.cumsum(array_cuadrados): Calcula la suma acumulativa de los valores en array_cuadrados.

array_raiz_quinta = np.power(array_cuadrados, 1/5).round(2): Calcula la raíz quinta de cada valor en array_cuadrados y redondea los resultados a 2 decimales.

Imprime los resultados de cada cálculo:

La media aritmética.
La desviación estándar.
El valor máximo.
El índice del valor máximo.
Los valores de output_array al cuadrado.
La suma acumulativa de los valores al cuadrado.
Los valores de array_raiz_quinta.
En resumen, este código realiza una serie de cálculos estadísticos y operaciones matemáticas sobre los valores en output_array y muestra los resultados.

##Ejercicio 2.3
Con los arrays que obtuvimos en la sección anterior:

Calcular el producto escalar (o producto punto) entre los array output y el array raiz quinta.
Crear un vector con los 3 ultimos valores del array input. Crear un segundo vector con los 3 primeros valores del array suma acumulativa de los cuadrados. Calcular el array que daria como resultado hacer el producto vectorial entre ambos.

In [41]:
resultado_producto_escalar = np.matmul(output_array,array_raiz_quinta).round(2)
resultado_producto_escalar

2744461.93

In [42]:
vector1 = input_array[-3:]
vector2 = suma_acumulativa_cuadrados[:3]
resultado_producto_vectorial = np.cross(vector1,vector2)
resultado_producto_vectorial

array([ 229102, -208604,    4462])

resultado_producto_escalar = np.matmul(output_array, array_raiz_quinta).round(2): Este código calcula el producto escalar entre output_array y array_raiz_quinta, redondeando el resultado a 2 decimales.

 El producto escalar es una operación entre dos vectores que produce un único escalar. En este caso, output_array y array_raiz_quinta deben tener la misma longitud para que el producto escalar pueda ser calculado.

vector1 = input_array[-3:]: Aquí se seleccionan los últimos tres elementos de input_array utilizando la indexación negativa. Es decir, se toman los elementos empezando desde el tercer elemento contando desde el final hasta el último.

vector2 = suma_acumulativa_cuadrados[:3]: En este caso, se seleccionan los primeros tres elementos de suma_acumulativa_cuadrados utilizando la indexación positiva. Es decir, se toman los tres primeros elementos de la lista.

resultado_producto_vectorial = np.cross(vector1, vector2): Este código calcula el producto vectorial entre vector1 y vector2. El producto vectorial es una operación entre dos vectores que produce un nuevo vector perpendicular a los vectores originales. El resultado es un vector tridimensional en el espacio euclidiano.