#INSTALAR MÓDULOS
A la hora de trabajar con módulos es posible que no los tengamos instalados ya que muchos son creados por la comunidad o simplemente no estan incluidos con los archivos base de python.

Para ello podemos usar pip:

En la terminal (local): pip install <nombre_modulo>
En colab ejecutar en una celda: !pip install <nombre_modulo>
#MATH
El módulo math en Python se utiliza para realizar operaciones matemáticas más avanzadas que las disponibles en el conjunto de funciones y permite utilizar constantes matemáticas básicas para manejar problemas más complejos que requieren operaciones matemáticas avanzadas..

Incluye funciones para:

Realizar cálculos trigonométricos
Operaciones de álgebra lineal
Funciones exponenciales y logarítmicas
##Ejercicio 1.0
Importar el módulo math

In [1]:
import math

##Ejercicio 1.1
Calculadora de Área de un Círculo

In [2]:
radio = float(input("Ingrese el radio del círculo: "))
area = math.pi * radio ** 2
print("El área del círculo es:", area)

Ingrese el radio del círculo: 56
El área del círculo es: 9852.03456165759


##Ejercicio 1.2
Calculadora de Hipotenusa

In [3]:
cateto1 = float(input("Ingrese la longitud del primer cateto: "))
cateto2 = float(input("Ingrese la longitud del segundo cateto: "))
hipotenusa = math.sqrt(cateto1 ** 2 + cateto2 ** 2)
print("La longitud de la hipotenusa es:", hipotenusa)

Ingrese la longitud del primer cateto: 4
Ingrese la longitud del segundo cateto: 2
La longitud de la hipotenusa es: 4.47213595499958


##Ejercicio 1.3
Calculadora seno, coseno, tangente

In [4]:
angulo_grados = float(input("Ingrese el ángulo en grados: "))
angulo_radianes = math.radians(angulo_grados)

seno = math.sin(angulo_radianes)
coseno = math.cos(angulo_radianes)
tangente = math.tan(angulo_radianes)

print("Seno:", seno)
print("Coseno:", coseno)
print("Tangente:", tangente)

Ingrese el ángulo en grados: 32
Seno: 0.5299192642332049
Coseno: 0.848048096156426
Tangente: 0.6248693519093275


##Ejercicio 1.4
Cálculo de Potencias

In [5]:
base = float(input("Ingrese la base: "))
exponente = float(input("Ingrese el exponente: "))
resultado = math.pow(base, exponente)
print("El resultado de", base, "elevado a la", exponente, "es:", resultado)

Ingrese la base: 2
Ingrese el exponente: 5
El resultado de 2.0 elevado a la 5.0 es: 32.0


##Ejercicio 1.5
Área de un Triángulo (fórmula de Herón)

In [6]:
lado1 = 5
lado2 = 6
lado3 = 7

s = (lado1 + lado2 + lado3) / 2

area = math.sqrt(s * (s - lado1) * (s - lado2) * (s - lado3))
print("El área del triángulo es:", area)


El área del triángulo es: 14.696938456699069


#NUMPY
NumPy es una biblioteca de Python que ayuda a trabajar con matrices y arreglos multidimensionales.

Con NumPy se puede realizar:


*   Multiplicación de matrices/arregleos
*   Inversión de matrices/arregleos
*   Cálculo de funciones trigonométricas
*   Procesamiento de datos
*   Manipulación de matrices grandes de manera rápida y eficiente.



En resumen NumPy se usa para trabajar con datos numéricos en Python.



##Ejercicio 2.0
Importar Numpy pero usando el alias np

In [1]:
import numpy as np

##Ejercicio 2.1
Veamos las operaciones basicas con arrays

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

suma = a + b
resta = a - b
multiplicacion = a * b
division = a / b

print ("suma:", suma)
print ("resta:", resta)
print ("multiplicacion:", multiplicacion)
print ("division:", division)

suma: [ 7  9 11 13 15]
resta: [-5 -5 -5 -5 -5]
multiplicacion: [ 6 14 24 36 50]
division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


##Ejercicio 2.2
Con numpy es muy facil crear matrices, por ejemplo la matriz de Identidad

In [9]:
matriz_identidad = np.eye(8)
print(matriz_identidad)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


no admite float y tampoco enteros negativos

##Ejercicio 2.3
Si trabajamos con vectores podemos calcular el producto escalar de estos

In [10]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

producto_escalar = np.dot(vector1, vector2)
print("Producto escalar:", producto_escalar)

Producto escalar: 32


que hace por detras (1 * 4)+(2 * 5)+(6 * 3) = 4 + 10 + 18 = 32

##Ejercicio 2.4
Otra operación muy común es calcular el vector norma

In [11]:
vector = np.array([3, 4])
norma = np.linalg.norm(vector)
print("Norma del vector:", norma)

Norma del vector: 5.0


Cómo calcular el módulo de un vector con sus componentes

Componentes de un vector

u--> = (a, b)

Un vector está definido por sus componentes y a partir de ellas podemos calcular su módulo aplicando la siguiente fórmula:

||u(vector)|| = (a al cuadrado + b al cuadrado) **1/2

Fórmula para calcular el módulo de un vector

##Ejercicio 2.5
De forma similar es posible realizar operaciones entre matrices usando Numpy

In [12]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

producto_matricial = np.matmul(matriz1, matriz2)
transpuesta = np.transpose(matriz1)
determinante = np.linalg.det(matriz1)

print("Producto matricial:")
print(producto_matricial)
print("Transpuesta de la matriz:")
print(transpuesta)
print("Determinante de la matriz:")
print(determinante)

Producto matricial:
[[19 22]
 [43 50]]
Transpuesta de la matriz:
[[1 3]
 [2 4]]
Determinante de la matriz:
-2.0000000000000004


Este es el resultado del producto matricial de matriz1 y matriz2. Cada elemento de la matriz resultante se calcula como se describió anteriormente. Por ejemplo, el primer elemento de la matriz resultante es 19, que se calcula como:

1
×
5
+
2
×
7
=
19


El segundo elemento de la matriz resultante es 22, que se calcula como:

1
×
6
+
2
×
8
=
22


Y así sucesivamente para los elementos restantes.

En resumen, dot tiene un comportamiento más general que matmul, ya que también puede realizar el producto punto de matrices multidimensionales, mientras que matmul está diseñado específicamente para el producto matricial y es más restrictivo en cuanto a las dimensiones de las matrices de entrada. Para operaciones de producto matricial, se recomienda utilizar matmul, ya que es más claro en su intención y puede ser más eficiente en ciertos casos.

.la transpuesta de una matriz es una operación en la que las filas de la matriz original se convierten en columnas en la matriz transpuesta y viceversa. En numpy, puedes obtener la transpuesta de una matriz utilizando el atributo T o la función transpose().

los elementos de las filas de la matriz original se convierten en columnas en la matriz transpuesta y viceversa.

La determinante de una matriz cuadrada es un número especial que se calcula a partir de los elementos de la matriz. En el caso de una matriz 2x2 como las que tenemos en nuestro ejemplo, la determinante se calcula mediante la fórmula:

|a  b|

|c  d|  = ad - bc

##Ejercicio 2.6
Numpy tiene una función especifica para resolver ecuaciones lineales

In [13]:
coeficientes = np.array([[2, 3], [4, -1]])
constantes = np.array([5, 2])

solucion = np.linalg.solve(coeficientes, constantes)
print("Solución del sistema de ecuaciones:")
print("x =", solucion[0])
print("y =", solucion[1])

Solución del sistema de ecuaciones:
x = 0.7857142857142857
y = 1.1428571428571428


2x + 3y = 5

4x -  y = 2


Se define un vector constantes que contiene los términos constantes de las ecuaciones del sistema. En este caso, el vector es [5, 2], lo que representa los términos constantes de las ecuaciones anteriores.

Se utiliza la función numpy.linalg.solve(coeficientes, constantes) para encontrar la solución del sistema de ecuaciones representado por la matriz de coeficientes y el vector de constantes. Esta función resuelve el sistema de ecuaciones lineales de la forma coeficientes * x = constantes, donde x es el vector de incógnitas.

La solución se almacena en la variable solucion. La solución es un vector que contiene los valores de las incógnitas que satisfacen todas las ecuaciones del sistema.

Finalmente, se imprime la solución del sistema de ecuaciones, mostrando los valores de las incógnitas x e y.

En resumen, este código calcula y muestra la solución de un sistema de ecuaciones lineales dados los coeficientes y los términos constantes de las ecuaciones.